import { z } from "zod";
export declare const PlanetAttachmentSchema: z.ZodReadonly<z.ZodObject<{
    name: z.ZodString;
    nsidName: z.ZodReadonly<z.ZodEffects<z.ZodString, string, string>>;
    imgFaceDown: z.ZodOptional<z.ZodBoolean>;
    doNotAttach: z.ZodOptional<z.ZodBoolean>;
    influence: z.ZodOptional<z.ZodNumber>;
    influenceFaceDown: z.ZodOptional<z.ZodNumber>;
    resources: z.ZodOptional<z.ZodNumber>;
    resourcesFaceDown: z.ZodOptional<z.ZodNumber>;
    techs: z.ZodOptional<z.ZodArray<z.ZodReadonly<z.ZodEnum<["blue", "green", "red", "yellow"]>>, "many">>;
    techsFaceDown: z.ZodOptional<z.ZodArray<z.ZodReadonly<z.ZodEnum<["blue", "green", "red", "yellow"]>>, "many">>;
    traits: z.ZodOptional<z.ZodArray<z.ZodReadonly<z.ZodEnum<["cultural", "hazardous", "industrial"]>>, "many">>;
    traitsFaceDown: z.ZodOptional<z.ZodArray<z.ZodReadonly<z.ZodEnum<["cultural", "hazardous", "industrial"]>>, "many">>;
    isLegendary: z.ZodOptional<z.ZodBoolean>;
    legendaryNsidName: z.ZodOptional<z.ZodString>;
    isDestroyPlanet: z.ZodOptional<z.ZodBoolean>;
    flipIfNoPlanetTech: z.ZodOptional<z.ZodBoolean>;
}, "strict", z.ZodTypeAny, {
    name: string;
    nsidName: string;
    influence?: number | undefined;
    resources?: number | undefined;
    techs?: ("blue" | "green" | "red" | "yellow")[] | undefined;
    traits?: ("cultural" | "hazardous" | "industrial")[] | undefined;
    isLegendary?: boolean | undefined;
    legendaryNsidName?: string | undefined;
    imgFaceDown?: boolean | undefined;
    doNotAttach?: boolean | undefined;
    influenceFaceDown?: number | undefined;
    resourcesFaceDown?: number | undefined;
    techsFaceDown?: ("blue" | "green" | "red" | "yellow")[] | undefined;
    traitsFaceDown?: ("cultural" | "hazardous" | "industrial")[] | undefined;
    isDestroyPlanet?: boolean | undefined;
    flipIfNoPlanetTech?: boolean | undefined;
}, {
    name: string;
    nsidName: string;
    influence?: number | undefined;
    resources?: number | undefined;
    techs?: ("blue" | "green" | "red" | "yellow")[] | undefined;
    traits?: ("cultural" | "hazardous" | "industrial")[] | undefined;
    isLegendary?: boolean | undefined;
    legendaryNsidName?: string | undefined;
    imgFaceDown?: boolean | undefined;
    doNotAttach?: boolean | undefined;
    influenceFaceDown?: number | undefined;
    resourcesFaceDown?: number | undefined;
    techsFaceDown?: ("blue" | "green" | "red" | "yellow")[] | undefined;
    traitsFaceDown?: ("cultural" | "hazardous" | "industrial")[] | undefined;
    isDestroyPlanet?: boolean | undefined;
    flipIfNoPlanetTech?: boolean | undefined;
}>>;
export type PlanetAttachmentSchemaType = z.infer<typeof PlanetAttachmentSchema>;
